apiVersion: v1
kind: ConfigMap
metadata:
  name: alpine-script
  namespace: test
data:
  job.sh: |
    #!/bin/sh
    echo "Running job at $(date)" >> /var/log/job.log
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alpine
  labels:
    run: alpine
spec:
  selector:
    matchLabels:
      run: alpine
  template:
    metadata:
      labels:
        run: alpine
    spec:
      imagePullSecrets:
      - name: my-registry-secret  # <-- Replace with your actual secret name
      containers:
      - name: alpine
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "chmod +x /scripts/job.sh && while true; do /scripts/job.sh; sleep 3600; done"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: alpine-script
          defaultMode: 0755
