---
- name: Extract Private Key from PEM File
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if input file exists
      ansible.builtin.stat:
        path: /tmp/example.pem
      register: input_file_stat

    - name: Fail if input file is missing
      ansible.builtin.fail:
        msg: "Input file /tmp/example.pem does not exist."
      when: not input_file_stat.stat.exists

    - name: Extract private key using sed
      ansible.builtin.shell: |
        sed -n '/-----BEGIN PRIVATE KEY-----/,/-----END PRIVATE KEY-----/p' /tmp/example.pem > /tmp/private_key.pem
      args:
        executable: /bin/bash
        creates: /tmp/private_key.pem  # Ensures idempotency

    - name: Verify private key extraction
      ansible.builtin.shell: |
        if grep -q "-----BEGIN PRIVATE KEY-----" /tmp/private_key.pem; then
          echo "Private key extracted successfully."
        else
          echo "Failed to extract private key."
          exit 1
        fi
      register: validation
      failed_when: validation.rc != 0

    - name: Display extracted private key (optional, for debugging)
      ansible.builtin.shell: cat /tmp/private_key.pem
