name: Call External Shell Script to Create Tag

on:
  workflow_dispatch:  # Trigger manually

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git Authentication
        run: |
          git config --global user.email "youremail@example.com"  # Replace with your email
          git config --global user.name "Your Name"  # Replace with your name

      - name: Make the Shell Script Executable
        run: chmod +x ./create-tag.sh  # Ensure the shell script has execute permissions

      - name: Call Shell Script to Create Tag
        run: ./create-tag.sh  # Run the shell script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Pass the GitHub token from repository secrets
          OWNER: your-github-username       # Replace with your GitHub username or organization
          REPO: your-repo-name              # Replace with your repository name
          TAG_NAME: v1.0.0                  # Replace with your desired tag name
          TAG_MESSAGE: "Release v1.0.0"     # Replace with your tag message
