---
- name: Extract and save certificate and private key from quoted cert_response
  hosts: localhost
  gather_facts: no
  vars:
    certificate_file: /path/to/certificate.pem  # Path to save the certificate
    private_key_file: /path/to/private_key.pem  # Path to save the private key
    cert_response: "\"-----BEGIN CERTIFICATE-----\nMIID0DCCArigAwIBAgIBATANBgkqhkiG9w0BAQUFADB/MQswCQYDVQQGEwJGUjET\nMBEGA1UECAwKU29tZS1TdGF0ZTEOMAwGA1UEBwwFUGFyaXMxDTALBgNVBAoMBERp\nbWkxDTALBgNVBAsMBE5TQlUxEDAOBgNVBAMMB0RpbWkgQ0ExGzAZBgkqhkiG9w0B\nCQEWDGRpbWlAZGltaS5mcjAeFw0xNDAxMjgyMDM2NTVaFw0yNDAxMjYyMDM2NTVa\nMFsxCzAJBgNVBAYTAkZSMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJ\nbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQxFDASBgNVBAMMC3d3dy5kaW1pLmZyMIIB\nIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvpnaPKLIKdvx98KW68lz8pGa\nRRcYersNGqPjpifMVjjE8LuCoXgPU0HePnNTUjpShBnynKCvrtWhN+haKbSp+QWX\nSxiTrW99HBfAl1MDQyWcukoEb9Cw6INctVUN4iRvkn9T8E6q174RbcnwA/7yTc7p\n1NCvw+6B/aAN9l1G2pQXgRdYC/+G6o1IZEHtWhqzE97nY5QKNuUVD0V09dc5CDYB\naKjqetwwv6DFk/GRdOSEd/6bW+20z0qSHpa3YNW6qSp+x5pyYmDrzRIR03os6Dau\nZkChSRyc/Whvurx6o85D6qpzywo8xwNaLZHxTQPgcIA5su9ZIytv9LH2E+lSwwID\nAQABo3sweTAJBgNVHRMEAjAAMCwGCWCGSAGG+EIBDQQfFh1PcGVuU1NMIEdlbmVy\nYXRlZCBDZXJ0aWZpY2F0ZTAdBgNVHQ4EFgQU+tugFtyN+cXe1wxUqeA7X+yS3bgw\nHwYDVR0jBBgwFoAUhMwqkbBrGp87HxfvwgPnlGgVR64wDQYJKoZIhvcNAQEFBQAD\nggEBAIEEmqqhEzeXZ4CKhE5UM9vCKzkj5Iv9TFs/a9CcQuepzplt7YVmevBFNOc0\n+1ZyR4tXgi4+5MHGzhYCIVvHo4hKqYm+J+o5mwQInf1qoAHuO7CLD3WNa1sKcVUV\nvepIxc/1aHZrG+dPeEHt0MdFfOw13YdUc2FH6AqEdcEL4aV5PXq2eYR8hR4zKbc1\nfBtuqUsvA8NWSIyzQ16fyGve+ANf6vXvUizyvwDrPRv/kfvLNa3ZPnLMMxU98Mvh\nPXy3PkB8++6U4Y3vdk2Ni2WYYlIls8yqbM4327IKmkDc2TimS8u60CT47mKU7aDY\ncbTV5RDkrlaYwm5yqlTIglvCv7o=\n-----END CERTIFICATE-----\n-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAvpnaPKLIKdvx98KW68lz8pGaRRcYersNGqPjpifMVjjE8LuC\n-----END RSA PRIVATE KEY-----\""

  tasks:
    - name: Remove quotes and split cert_response into lines
      set_fact:
        cert_lines: "{{ cert_response | regex_replace('^\"|\"$', '') | from_yaml | splitlines() }}"

    - name: Extract the certificate content
      set_fact:
        certificate_content: >-
          {{ cert_lines | select('search', '-----BEGIN CERTIFICATE-----') 
                        | map('regex_replace', '-----BEGIN CERTIFICATE-----|-----END CERTIFICATE-----', '') 
                        | join('\n') | trim }}

    - name: Extract the private key content
      set_fact:
        private_key_content: >-
          {{ cert_lines | select('search', '-----BEGIN RSA PRIVATE KEY-----') 
                        | map('regex_replace', '-----BEGIN RSA PRIVATE KEY-----|-----END RSA PRIVATE KEY-----', '') 
                        | join('\n') | trim }}

    - name: Save the cleaned certificate to a file
      copy:
        content: "{{ certificate_content }}"
        dest: "{{ certificate_file }}"
        mode: '0600'

    - name: Save the cleaned private key to a file
      copy:
        content: "{{ private_key_content }}"
        dest: "{{ private_key_file }}"
        mode: '0600'
