---
- name: Extract Private Key from PEM File
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Normalize file and extract private key
      ansible.builtin.shell: |
        sed -n '/-----BEGIN PRIVATE KEY-----/,/-----END PRIVATE KEY-----/p' /tmp/example.pem | tr -d '\r' > /tmp/private_key.pem
      args:
        creates: /tmp/private_key.pem  # Prevents overwriting if the file already exists

    - name: Validate private key content
      ansible.builtin.shell: |
        if ! grep -q "-----BEGIN PRIVATE KEY-----" /tmp/private_key.pem; then
          echo "Private key extraction failed"
          exit 1
        fi
      register: validate_key
      failed_when: validate_key.rc != 0

    - name: Display private key content (optional for debugging)
      ansible.builtin.shell: cat /tmp/private_key.pem
