---
- name: Extract Private Key using sed
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Extract private key from PEM file
      ansible.builtin.shell: |
        sed -n '/-----BEGIN PRIVATE KEY-----/,/-----END PRIVATE KEY-----/p' /tmp/example.pem > /tmp/private_key.pem
      args:
        removes: /tmp/private_key.pem  # Ensures idempotency by removing the output file if it exists

    - name: Display extracted private key (optional, for debugging)
      ansible.builtin.shell: cat /tmp/private_key.pem
